### PR TITLE
CRAB-32888: Handle NaT in Capsule start/end when filling template

### PR DESCRIPTION
**Pull request by andre-rigon**
When filling templates display NaT in a Capsule's start or end as "-".

---

### Merge Criteria

**Primary reviewer**
Volunteer?

**Knowledge base**
N/A

**Compatibility breaks**
N/A

**Security considerations**
N/A

**Exploratory functional testing**

- Started a Jupyter Notebook in Seeq with `. environment && cd sdk && sq run` and copied the connection URL with token
- Opened the EmailNotificationAddOn project in VSCode and installed the Jupyter extension
- Connected to the running Jupyter Notebook with the copied URL
- Executed the cell with several `import`s and the cell containing the `fill_in_template` function declaration
- Executed the following test code:

```
my_template = """
    Capsule Start: {capsule["Capsule Start"]}
    Capsule End: {capsule["Capsule End"]}
"""
my_capsule = {
    "Capsule Start": datetime.fromisoformat('2011-11-04'),
    "Capsule End": pd.NaT
}
my_job = {"Time Zone": "US/Eastern"}
print(fill_in_template(my_template, my_capsule, my_job))
```

which printed

```
    Capsule Start: 2011-11-03T23:00:00-04:00
    Capsule End: -
```

**Regression testing**
N/A

**Product Owner acceptance**
@cherrera2001 

**Presentation slide**
N/A

### CODE REVIEW

**Comment by andre-rigon** [comment]
> LGTM! You can put me as primary if @cherrera2001 is willing to do the exploratory testing. 😁

Thank you, @DJamesP !

**Comment by cherrera2001** [comment]
@DJamesP @andre-rigon sure thing, I will test.

**Review by mar1u50 — APPROVED** [review]

**Review by cherrera2001 — APPROVED** [review]

**Comment by cherrera2001** [comment]
Exploratory Testing Notes:
✅ created a manual condition that exceeded the bounds of the pull and returned an NaT for the end time
✅ the email was generated and showed a - for the end time
✅ created a manual condition and queried for a range that was a subset of the capsule range (spy pull showed NaT for start / end)
✅ the email was generated with - for start / end

**Comment by andre-rigon** [comment]
Thank you for testing, @cherrera2001 !

**Comment by andre-rigon** [comment]
@mergefast --squash

**Pull request merged**
